### PR TITLE
Add single quotes, dotted.mixed.case to v3.0.1

### PR DESCRIPTION
**Pull request by madisonjordan**
## Migration Notes

version: r-lib v3.0.1.9000 (development) as of 2022-09-16

<h4> Summary of Changes:</h4>
<blockquote>
<ul>
<li><p>set modifications/params on default linters to use in  <code>.lintr</code> (main config)</p></li>
<li><p>add dotted.mixed.case </p></li>
<li><p>change single quote linting behavior</p></li>
<li><p>remove unnecessary r-lib GitHub Actions </p></li>
</ul>
</blockquote>

--- 
#### Config changes

- Update linters in `.lintr` (main config file)
- Update defaults used in test action `tests/testthat/dummy_packages/package/lintr_test_config`

#### Dotted.Mixed.Case

Updates required:
- `R/object_name_lintr.R`
   - add `dotted.mixed.case`(different from `dotted.case`) 
   - ```
     "dotted.mixed.case" = rex(start, maybe("."), one_or_more(alphanum), zero_or_more(dot, one_or_more(alphanum)), end),
     ```
Test case files:
- `test-object_name_lintr.R`
   - update test case matrix for `dotted.mixed.case` (same values as `dotted.case` but allow "Uppercase")
   - update message (the one with dotted.case) to include `dotted.mixed.case`
       - "Variable and function name style should be camelCase, dotted.case or dotted.mixed.case." 
       - Note: no comma before "or". See logic in object_name_lintr.

#### Single Quotes (lab version)

Updates required for using lab's single_quote:
- `R/single_quotes_lintr.R`
    - replace text to say single-quote instead of double-quote
    - change `squote_regex`
  ```
  squote_regex <- rex(start, zero_or_one(character_class("rR")), double_quote, any_non_single_quotes, double_quote, end)
  ```
For all of the test case files:
- replace every double quote `"` with single quote `'` and vice versa (only if it's text in a test)
- replace message text to say `single-quote` instead of `double-quote`

Test case files:
- `inst/example/bad.R` 
- `tests/test-single_quotes_lintr`
- `tests/testthat/dummy_packages/clean/R/clean_generics.R`
- `tests/testthat/dummy_packages/clean/R/default_lintr_testcode.R`
- `tests/testthat/test-knitr_formats.R`

#### GitHub Actions:
- remove GitPages deployment 
      - `pkgdown` files
- disable R linting "Error on Lint Failure" on the Git Action for this package <br>&emsp;___Note:___ _Will cause fails from `r-lib` not using `single quotes` or `dotted.mixed.case`_

### CODE REVIEW

**Comment by madisonjordan** [comment]
@tyamaguchi-ucla I'm down to 8 errors in the checks now. 6 errors are related to "exclusions" (`#nolint`) and 2 errors are related to "all default linters are tagged default". I'm still looking into those, but I might be stuck. You can see them in the action `test-packages`. 
I definitely appeared to update all the tests that are obviously for single quotes and mixed quotes new behavior now. Do you want me to try running tests on some scripts/packages now, or wait until I fix the last 8 errors, if I can?

Also, do you want me to create a PR for the changes only done by the r-lib update to v3.0.1.9000 (branch `r-lib_v3...`) into master first? It might be easier to see what changes I made on top of those from this PR after that.

**Comment by tyamaguchi-ucla** [comment]
> @tyamaguchi-ucla I'm down to 8 errors in the checks now. 6 errors are related to "exclusions" (`#nolint`) and 2 errors are related to "all default linters are tagged default". I'm still looking into those, but I might be stuck. You can see them in the action `test-packages`. I definitely appeared to update all the tests that are obviously for single quotes and mixed quotes new behavior now. Do you want me to try running tests on some scripts/packages now, or wait until I fix the last 8 errors, if I can?
> 
> Also, do you want me to create a PR for the changes only done by the r-lib update to v3.0.1.9000 (branch `r-lib_v3...`) into master first? It might be easier to see what changes I made on top of those from this PR after that.

Let me add @stefaneng @dan-knight @jarbet as I'm not familiar with the specific errors.

**Comment by tyamaguchi-ucla** [comment]
> Also, do you want me to create a PR for the changes only done by the r-lib update to v3.0.1.9000 (branch `r-lib_v3...`) into master first? It might be easier to see what changes I made on top of those from this PR after that.

Yes, this makes sense to me.

**Comment by madisonjordan** [comment]
I think I understand the logic for the exclusions test, but I don't know why it doesn't work now. I don't think I even changed anything related to that. Maybe the settings somewhere?

This is the related code to the failing 6 errors:
https://github.com/uclahs-cds/lintr/blob/114644c1fc8ac15a037699cfd6531384f733e2e1/tests/testthat/test-exclusions.R#L16-L44

- I think `t1` is just "how many lines are there in the [tests/testthat/exclusions-test](https://github.com/uclahs-cds/lintr/blob/master/tests/testthat/exclusions-test) if you don't include blank lines or the exclusions" 
eg. nolint start, end, nolint. 
but "nolint: assignment" isn't fully excluded since it still needs to process that line for other linters.
- `t2` should be if you removed line 4 in the exclusions-test file.  so that would be `t1` - 1 = 7
- `t3` (which passes) is if you removed the entire file I guess? so that should be 0.
- `t4` I think uses the cached results so that probably fails since `t1` and `t2` did

I counted manually for `t1` and I get 8 so I don't know why this is getting 7.

**Comment by madisonjordan** [comment]
I think "all default linters are tagged default" is supposed to fail, so those 2 aren't technically errors. Because I changed the defaults and would fail the same reason it would in `covr` described in the comments. The `test-coverage` action shows 6 errors just for the exclusion and not the default tag errors since it skips that one test.

https://github.com/uclahs-cds/lintr/blob/7a1bb4eec7924d1095c82093fd956e60d70847ec/tests/testthat/test-with.R#L20-L23

I'm not sure what to do to handle that for our modifications the same way it is for `covr`.

**Comment by madisonjordan** [comment]
For future reference:
It was a configuration issue. You're not supposed to add params in any of the linters to change the defaults behavior in the `zzz.R` file. That's where the "generic" defaults go. The default params are modified in the `.lintr` config file, which is also where you can disable specified linters. 

I'll put this in some documentation later along with some of the other instructions so hopefully no one (or me if I forget) has to figure this all out again whenever there's another breaking update.

**Comment by dan-knight** [comment]
Looks good to me!

Note outside the scope of this PR: I wonder if forking the repo and altering the source is the way that r-lib intends users to customize the package. If I remember correctly, you can create custom rules separately, and just use a normal installation of the lintr package. If this becomes a pain to maintain, we might consider looking into it.

**Review by dan-knight — APPROVED** [review]

**Comment by madisonjordan** [comment]
@dan-knight 
> Note outside the scope of this PR: I wonder if forking the repo and altering the source is the way that r-lib intends users to customize the package. If I remember correctly, you can create custom rules separately, and just use a normal installation of the lintr package. If this becomes a pain to maintain, we might consider looking into it.

my answer to this was crazy long as usual so I put it in #7 instead as a discussion since it didn't seem to qualify as an issue until it's decided how exactly we'd like to address this and I can create tasks for it.

**Comment by jarbet** [comment]
Great work!

I'm wondering if we should have a test file with at least 1 example per lintr rule we want to use, where we expect the example to violate the lintr rule.  Then when someone proposes a PR, they can run the test file and save the output somewhere on `/hot/` for reviewers, just to make sure everything is working as expected?

Or is this already being done by the "Test case files" you listed?  If yes, how can we verify the results are correct?

**Review by jarbet — COMMENTED** [review]
Great work!

I'm wondering if we should have a test file with at least 1 example per lintr rule we want to use, where we expect the example to violate the lintr rule. Then when someone proposes a PR, they can run the test file and save the output somewhere on /hot/ for reviewers, just to make sure everything is working as expected?

Or is this already being done by the "Test case files" you listed? If yes, how can we verify the results are correct?

**Comment by madisonjordan** [comment]
@jarbet 
> Or is this already being done by the "Test case files" you listed? If yes, how can we verify the results are correct?

Yes, but so far I have only implemented the single quotes and dotted.mixed.case. The other linters are using the defaults so we are using those rules until I look at the lab standards in much greater detail or get clarification from Paul or something. For the already implemented linters, they are tested independent of the parameters passed, for example the line length linter default is 80 characters, but even if it's changed to 120, the logic from the tests is the same and will behave the same if the function logic allows for that character length. And that should be verified by the tests.

Unit testing is done by [`covr` package](https://cran.r-project.org/web/packages/covr/vignettes/how_it_works.html) in the CICD GitHub action. On my own R scripts the added lab behavior for variables and quotes was working as intended, but I had to modify the tests in the CICD here to make sure it worked beyond just what I had checked. The functional changes for the lints themselves only took 20 minutes since we already had it from the last version. 

Verifying they are correct would be something that is defined before creating the tests, as in "if they do something like this should it fail or pass?". They have helper functions that basically check to see if it outputs the correct message and gives the expected result. `expect_fail` and `expect_success` in addition to `expect_identical` function. 

This is the best example of this:
https://github.com/uclahs-cds/lintr/blob/181a2ed7fa30911a0d2c29741a59d9f4e6aa6073/tests/testthat/test-object_name_linter.R#L5-L37

It's a table that has generic test cases representative of all the possible variable formats someone could put, I added a column for dotted.mixed.case, which is the same as dotted.case but allows for uppercase letters, such as `aaBBC.dd.E` will pass. If we only want it to pass like `AAbbc.DD.e` then that would require me changing the tests to know when it isn't working and then the regex for the rule, since it's not sophisticated enough to determine whether uppercase is okay after a lowercase within the substring separated by dots.

The single quotes test is very extensive right now because I changed their "prefer double quote" code to be single quote. There is a `test-single_quote` file that does every possible test they could think of, which I had to modify. It even includes R strings, which was added in R 4.0.0. example `r"(test\string)"`.

If we decided to make our own test cases and not modify it, then it would be a good idea to put every test case we could think of the way they did in their linter-specific tests. And that's more or less how you verify it's correct until a user finds a way to break it that you hadn't considered and isn't handled.

**Comment by madisonjordan** [comment]
I'll make a note for myself to add some basic information for testing procedure to the docs for PRs and I'll update it when more feedback and suggestions come up around it. That was a good point @jarbet. Maybe there can be a PR for creating the test first that is reviewed before someone implements the linter corresponding to that test.

**Comment by madisonjordan** [comment]
@stefaneng anything else to add? Including questions or feedback that I would add to a discussion for us to decide on or if there's more things I might need to clarify in the documentation for usage, testing, maintaining with the strategy we have right now for implementing this.

**Comment by stefaneng** [comment]
> @stefaneng anything else to add? Including questions or feedback that I would add to a discussion for us to decide on or if there's more things I might need to clarify in the documentation for usage, testing, maintaining with the strategy we have right now for implementing this.

It seems like it would make sense to write a new function `double_quotes_lintr` rather than edit how `single_quotes_lintr` is defined. Otherwise we swapped the language usage from upstream (`single_quotes_lintr` mean enforce double quotes).

Zooming out a bit.. this does make me think that we are creating so much work for ourselves by having an alternative R standard from the community. For example, Ratliff indent, single quotes, semi-colon all clearly are hard to enforce using R community tools and IDEs. I guess this is probably outside of the scope of this PR though but maybe worth a discussion.

**Comment by madisonjordan** [comment]
> It seems like it would make sense to write a new function `double_quotes_lintr` rather than edit how `single_quotes_lintr` is defined. Otherwise we swapped the language usage from upstream (`single_quotes_lintr` mean enforce double quotes).
> 
> Zooming out a bit.. this does make me think that we are creating so much work for ourselves by having an alternative R standard from the community. For example, Ratliff indent, single quotes, semi-colon all clearly are hard to enforce using R community tools and IDEs. I guess this is probably outside of the scope of this PR though but maybe worth a discussion.

@stefaneng 
I agree with all of this. I discussed this in #7 about the process to create new linters. I also basically put some options of what we could do in there, but I should add a solution option where we use the defaults and don't maintain this at all as you mentioned. The ideal scenario would be to have as few modifications as possible from an implementation and maintenance standpoint, especially modifications that can just be a configuration and are already allowed by the function. For example, line_length is easily set to 120 characters in the `.lintr` config instead of the default 80. 

The Ratliff indent would be the hardest probably, but the semicolon and single quotes would be easy enough (in theory) to modify by adding a new linter and tests. I've also added issues for each of the linters with some tips for which files to use as a template.

Other than that, I would like to just start over now that I know more from this experience. I'd have to take additional time to figure out how they configured the tests to include the new test cases for our custom linters, unfortunately. I'm not sure how urgent it is to get just something that is working. But new linters/tests are how I'm planning on going moving forward at the very least. Not that I really have a choice since most of the tests would have to be created or rewritten entirely for the remaining linters anyway.

**Comment by madisonjordan** [comment]
Creating new linters instead. New lab quotes linter in #19

**Pull request closed without merging**
